# Generated by Django 4.1.13 on 2025-02-24 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0003_remove_profile_customauth__user_id_9ef4a5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from name', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='customauth__user_id_9ef4a5_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['slug'], name='customauth__slug_9706b5_idx'),
        ),
    ]
