# Generated by Django 4.1.13 on 2025-02-22 10:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_alter_directmessageuser_friends_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',), 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('name',), 'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AddField(
            model_name='userstatusmodel',
            name='chat_theme',
            field=models.CharField(default='light', max_length=20, verbose_name='Chat Theme'),
        ),
        migrations.AddField(
            model_name='userstatusmodel',
            name='custom_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom Status'),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the country was created.', verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Mark as active if the country is currently available.', verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Enter the official country name.', max_length=220, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated slug from the country name.', max_length=220, unique=True, verbose_name='Country Slug'),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the country was last updated.', verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(help_text='Select the country this state belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='chatroom.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the state was created.', verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(help_text='Enter the state name.', max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='State Name'),
        ),
        migrations.AlterField(
            model_name='state',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the state was last updated.', verbose_name='Updated Date'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name'], name='chatroom_co_name_48f509_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['slug'], name='chatroom_co_slug_918c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['name'], name='chatroom_st_name_fc6115_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['country', 'name'], name='chatroom_st_country_3be7b1_idx'),
        ),
    ]
